services:
  flask:
    build:
      context: beflask
    ports:
      - 8003:8003

  node:
    build:
      context: be-node
    environment:
      NODE_ENV: production
    ports:
      - 8001:8001

  go:
    build:
      context: be-go
      target: final
    ports:
      - 8002:8002
